server:
  port: 1001
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka
    fetch-registry: false
    register-with-eureka: false
