spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/leyou
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
server:
  port: 2001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
mybatis:
  type-aliases-package: org.tj.springcloud.user.model
  mapper-locations: mappers/*.xml
