spring:
  application:
    name: sysgateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: goods
          uri: lb://goods-service
          predicates:
            - Path=/goodsApi/**
          filters:
            - StripPrefix= 1
            - name: RequestRateLimiter #请求数限流 名字不能随便写
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10 #令牌桶每秒填充平均速率
                redis-rate-limiter.burstCapacity: 100 #令牌桶总容量
        - id: orders
          uri: lb://orders-service
          predicates:
            - Path=/orderApi/**
          filters:
            - StripPrefix= 1
  redis:
    host: 127.0.0.1
server:
  port: 9101
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka
  instance:
    prefer-ip-address: true