spring:
  application:
    name: search-service
#  data:
#    elasticsearch:
#      cluster-name: elasticsearch
#      cluster-nodes: 192.168.30.132:9200
#      repositories:
#        enabled: true
# datasource:
#   url: jdbc:mysql://localhost:3306/shop_user
#   driver-class-name: com.mysql.jdbc.Driver
#   username: root
#   password: 123
#   # Hikari 连接池配置
#   # 最小空闲连接数量
#   type: com.zaxxer.hikari.HikariDataSource
#   hikari:
#     minimum-idle: 5
#     # 空闲连接存活最大时间，默认600000（10分钟）
#     idle-timeout: 180000
#     # 连接池最大连接数，默认是10
#     maximum-pool-size: 10
#     # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
#     auto-commit: true
#     # 连接池名称
#     pool-name: MyHikariCP
#     # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
#     max-lifetime: 1800000
#     # 数据库连接超时时间,默认30秒，即30000
#     connection-timeout: 30000
#     connection-test-query: SELECT 1
# redis:
#   database: 0
#   host: localhost
#   port: 6379
#   jedis:
#     pool:
#       max-active: 500
#       max-idle:  1000
#       max-wait: 6000ms
#       min-idle: 4
server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
mybatis:
  type-aliases-package: org.tj.springcloud.common.model
  mapper-locations: mappers/*.xml
shop:
  worker:
    workerId: 1
    dataCenterId: 1
logging:
  level:
    org.tj.springcloud.search.mapper: debug

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 20000
