server:
  port: 10010
spring:
  application:
    name: api-proxy
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  prefix: /api
  routes:
    goods-service: /goods/**
  add-host-header: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
ribbon:
  connetTimeout: 500
  readTimeout: 5000