server:
  port: 10010
  connection-timeout: 5000
spring:
  application:
    name: api-proxy
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka
    registry-fetch-interval-seconds: 5
    eureka-server-read-timeout-seconds: 5

  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  prefix: /api
  routes:
    goods-service: /goods/**
    orders-service: /orders/**
  add-host-header: true
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            RimeoutInMilliseconds: 5000

ribbon:
  ConnetTimeout: 5000
  ReadTimeout: 5000

