server:
  port: 10010
spring:
  application:
    name: api-proxy
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:1001/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  prefix: /api
  routes:
    item-service: /item/**
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order-service/**
    upload-service:
      path: /upload/**
      service: upload-service
      strip-prefix: false
    search-service: /search/**
  sensitive-headers:
  add-host-header: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000
ribbon:
  connetTimeout: 500
  readTimeout: 5000