spring:
  application:
    name: orders-service
  datasource:
    url: jdbc:mysql://localhost:3306/shop_order
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
    # Hikari 连接池配置
    # 最小空闲连接数量
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 10
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 连接池名称
      pool-name: MyHikariCP
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 500
        max-idle:  1000
        max-wait: 6000ms
        min-idle: 4
server:
  port: 3001
  http2:
    enabled: true
    undertow:
      io-threads: 16
      worker-threads: 256
      buffer-size: 1024
      #buffers-per-region: 1024
      direct-buffers: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
mybatis-plus:
  type-aliases-package: org.tj.springcloud.common.model
  mapper-locations: mappers/*.xml
shop:
  worker:
    workerId: 1
    dataCenterId: 1
logging:
  level:
    org.tj.springcloud.user.mapper: debug
feign:
  hystrix:
    enabled: true

