spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3306/shop_user
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 500
        max-idle:  1000
        max-wait: 6000ms
        min-idle: 4
server:
  port: 6001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka
mybatis:
  type-aliases-package: org.tj.springcloud.common.model
  mapper-locations: mappers/*.xml
shop:
  worker:
    workerId: 1
    dataCenterId: 1
logging:
  level:
    org.tj.springcloud.user.mapper: debug

feign:
  hystrix:
    enabled: true
  client:
    config:
      default:   #配置全局的feign的调用超时时间  如果 有指定的服务配置 默认的配置不会生效
        connectTimeout: 60000 # 指定的是 消费者 连接服务提供者的连接超时时间 是否能连接  单位是毫秒
        readTimeout: 20000  # 指定的是调用服务提供者的 服务 的超时时间（）  单位是毫秒
#hystrix 配置
hystrix:
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制
          enabled: true
        isolation:
          strategy: SEMAPHORE
          thread:
            # 熔断器超时时间，默认：1000/毫秒
            timeoutInMilliseconds: 20000
